name: example

on: 
  push:

jobs:

  test:
    runs-on: ubuntu-20.04
    strategy:
        fail-fast: false
        matrix:
          os: [ macos-latest, windows-latest, ubuntu-latest ]
          java: [ '8', '11', '17']
    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{matrix.java}}
      - run: mvn test
